#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenVisualization.Data.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="oms")]
	public partial class OmsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public OmsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["omsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OmsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OmsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OmsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OmsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Query> Queries
		{
			get
			{
				return this.GetTable<Query>();
			}
		}
	}
	
	[Table(Name="dbo.Query")]
	public partial class Query
	{
		
		private string _sensor_id;
		
		private System.DateTime _read_date;
		
		private int _sensor_type;
		
		private string _sensor_rev;
		
		private string _sensor_config_rev;
		
		private string _gway_id;
		
		private int _gway_type;
		
		private string _gway_rev;
		
		private string _gway_config_rev;
		
		private int _gway_seq_nbr;
		
		private string _network_id;
		
		private int _site_nbr;
		
		private string _data_sentence;
		
		private System.Nullable<decimal> _battery_voltage;
		
		private System.Nullable<decimal> _temperature;
		
		private System.Nullable<decimal> _humidity;
		
		private System.Nullable<decimal> _wood_pct;
		
		private System.Nullable<decimal> _aux_voltage;
		
		private System.DateTime _create_date;
		
		private System.Nullable<decimal> _gpp;
		
		private System.Nullable<decimal> _dew_point;
		
		private System.Nullable<decimal> _gallons;
		
		public Query()
		{
		}
		
		[Column(Storage="_sensor_id", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sensor_id
		{
			get
			{
				return this._sensor_id;
			}
			set
			{
				if ((this._sensor_id != value))
				{
					this._sensor_id = value;
				}
			}
		}
		
		[Column(Storage="_read_date", DbType="DateTime NOT NULL")]
		public System.DateTime read_date
		{
			get
			{
				return this._read_date;
			}
			set
			{
				if ((this._read_date != value))
				{
					this._read_date = value;
				}
			}
		}
		
		[Column(Storage="_sensor_type", DbType="Int NOT NULL")]
		public int sensor_type
		{
			get
			{
				return this._sensor_type;
			}
			set
			{
				if ((this._sensor_type != value))
				{
					this._sensor_type = value;
				}
			}
		}
		
		[Column(Storage="_sensor_rev", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sensor_rev
		{
			get
			{
				return this._sensor_rev;
			}
			set
			{
				if ((this._sensor_rev != value))
				{
					this._sensor_rev = value;
				}
			}
		}
		
		[Column(Storage="_sensor_config_rev", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string sensor_config_rev
		{
			get
			{
				return this._sensor_config_rev;
			}
			set
			{
				if ((this._sensor_config_rev != value))
				{
					this._sensor_config_rev = value;
				}
			}
		}
		
		[Column(Storage="_gway_id", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gway_id
		{
			get
			{
				return this._gway_id;
			}
			set
			{
				if ((this._gway_id != value))
				{
					this._gway_id = value;
				}
			}
		}
		
		[Column(Storage="_gway_type", DbType="Int NOT NULL")]
		public int gway_type
		{
			get
			{
				return this._gway_type;
			}
			set
			{
				if ((this._gway_type != value))
				{
					this._gway_type = value;
				}
			}
		}
		
		[Column(Storage="_gway_rev", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gway_rev
		{
			get
			{
				return this._gway_rev;
			}
			set
			{
				if ((this._gway_rev != value))
				{
					this._gway_rev = value;
				}
			}
		}
		
		[Column(Storage="_gway_config_rev", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gway_config_rev
		{
			get
			{
				return this._gway_config_rev;
			}
			set
			{
				if ((this._gway_config_rev != value))
				{
					this._gway_config_rev = value;
				}
			}
		}
		
		[Column(Storage="_gway_seq_nbr", DbType="Int NOT NULL")]
		public int gway_seq_nbr
		{
			get
			{
				return this._gway_seq_nbr;
			}
			set
			{
				if ((this._gway_seq_nbr != value))
				{
					this._gway_seq_nbr = value;
				}
			}
		}
		
		[Column(Storage="_network_id", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string network_id
		{
			get
			{
				return this._network_id;
			}
			set
			{
				if ((this._network_id != value))
				{
					this._network_id = value;
				}
			}
		}
		
		[Column(Storage="_site_nbr", DbType="Int NOT NULL")]
		public int site_nbr
		{
			get
			{
				return this._site_nbr;
			}
			set
			{
				if ((this._site_nbr != value))
				{
					this._site_nbr = value;
				}
			}
		}
		
		[Column(Storage="_data_sentence", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string data_sentence
		{
			get
			{
				return this._data_sentence;
			}
			set
			{
				if ((this._data_sentence != value))
				{
					this._data_sentence = value;
				}
			}
		}
		
		[Column(Storage="_battery_voltage", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> battery_voltage
		{
			get
			{
				return this._battery_voltage;
			}
			set
			{
				if ((this._battery_voltage != value))
				{
					this._battery_voltage = value;
				}
			}
		}
		
		[Column(Storage="_temperature", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> temperature
		{
			get
			{
				return this._temperature;
			}
			set
			{
				if ((this._temperature != value))
				{
					this._temperature = value;
				}
			}
		}
		
		[Column(Storage="_humidity", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> humidity
		{
			get
			{
				return this._humidity;
			}
			set
			{
				if ((this._humidity != value))
				{
					this._humidity = value;
				}
			}
		}
		
		[Column(Storage="_wood_pct", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> wood_pct
		{
			get
			{
				return this._wood_pct;
			}
			set
			{
				if ((this._wood_pct != value))
				{
					this._wood_pct = value;
				}
			}
		}
		
		[Column(Storage="_aux_voltage", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> aux_voltage
		{
			get
			{
				return this._aux_voltage;
			}
			set
			{
				if ((this._aux_voltage != value))
				{
					this._aux_voltage = value;
				}
			}
		}
		
		[Column(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[Column(Storage="_gpp", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> gpp
		{
			get
			{
				return this._gpp;
			}
			set
			{
				if ((this._gpp != value))
				{
					this._gpp = value;
				}
			}
		}
		
		[Column(Storage="_dew_point", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> dew_point
		{
			get
			{
				return this._dew_point;
			}
			set
			{
				if ((this._dew_point != value))
				{
					this._dew_point = value;
				}
			}
		}
		
		[Column(Storage="_gallons", DbType="Decimal(9,0)")]
		public System.Nullable<decimal> gallons
		{
			get
			{
				return this._gallons;
			}
			set
			{
				if ((this._gallons != value))
				{
					this._gallons = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
